name: Production Release Tauri App

on:
    release:
        types: [published] # This workflow runs ONLY when a new release is published

jobs:
    build-tauri:
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, ubuntu-latest, windows-latest]

        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Setup Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: stable
                  target: ${{ matrix.platform == 'macos-latest' && 'x86_64-apple-darwin' || matrix.platform == 'ubuntu-latest' && 'x86_64-unknown-linux-gnu' || 'x86_64-pc-windows-msvc' }}
                  components: rustfmt, clippy
                  targets: |
                      x86_64-apple-darwin
                      x86_64-unknown-linux-gnu
                      x86_64-pc-windows-msvc

            - name: Install dependencies (Linux)
              if: matrix.platform == 'ubuntu-latest'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

            - name: Install frontend dependencies
              run: npm install # Or yarn install

            - name: Build Tauri app
              run: npm run tauri build # Or yarn tauri build

            - name: Upload release asset
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/') # Safety check: ensure triggered by a tag
              with:
                  # This correctly selects the artifact path for the current platform
                  files: |
                      ${{ matrix.platform == 'macos-latest' && 'src-tauri/target/release/bundle/dmg/*.dmg' || '' }}
                      ${{ matrix.platform == 'windows-latest' && 'src-tauri/target/release/bundle/msi/*.msi' || '' }}
                      ${{ matrix.platform == 'ubuntu-latest' && 'src-tauri/target/release/bundle/deb/*.deb' || '' }}
                  name: ${{ github.event.release.name || github.ref_name }}
                  tag_name: ${{ github.ref }}
                  body: ${{ github.event.release.body }}
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
